/* Generates src/app.cjs — every route file mounted at the same path
   server/index.js uses, with the same guards.

   Generated rather than hand-written so it cannot drift: if a mount is
   added or a guard changed on Render, re-running this picks it up. A
   hand-maintained list of 58 mounts is a list that goes stale silently,
   and a missing guard is a permission hole.

   Run: node tools/gen-app.js
*/
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const INDEX = path.join(HERE, "..", "..", "server", "index.js");
const OUT = path.join(HERE, "..", "src", "app.cjs");

const src = fs.readFileSync(INDEX, "utf8");
const re = /app\.use\("(\/api\/[a-z-]+)",\s*([^;]*?)require\("\.\/routes\/([a-zA-Z]+)"\)\)/g;

const rows = [];
let m;
while ((m = re.exec(src))) {
  rows.push({ mount: m[1], guards: m[2].trim().replace(/,\s*$/, ""), mod: m[3] });
}
if (!rows.length) { console.error("parsed no mounts — has server/index.js changed shape?"); process.exit(1); }

/* /api/auth stays with the Worker: it owns the signed cookie and the
   Durable Object session store, and that path is already tested. The
   copied routes/auth.js expects express-session and the tenant map, so
   mounting it here would fight the Worker for the same URLs. */
const SKIP = new Set(["/api/auth"]);
const kept = rows.filter((r) => !SKIP.has(r.mount));

const L = [];
L.push("/* GENERATED by tools/gen-app.js — do not edit by hand.");
L.push(`   ${kept.length} of ${rows.length} mounts; /api/auth is handled by the Worker.`);
L.push("   Regenerate after any change to server/index.js. */");
L.push('const express = require("./express-shim.cjs");');
L.push('const { requireAuth, requireRole } = require("../server/auth");');
L.push('/* Re-exported so the Durable Object uses the SAME module instance the');
L.push('   route files do. Reaching _runtime through a separate ESM import()');
L.push('   creates a second AsyncLocalStorage, and a store set on one is');
L.push('   invisible to the other — which presents as "used outside a request"');
L.push('   on every route while the wiring looks correct. */');
L.push('const runtime = require("../server/_runtime");');
L.push("");
L.push("function buildApp() {");
L.push("  const app = express.Router();");
for (const r of kept) {
  /* The regex captures guards with their trailing comma ("requireAuth,"),
     which is stripped when parsing and must be put back when emitting —
     otherwise the generated file reads `requireAuth require(...)`. */
  const guards = r.guards ? r.guards.replace(/\s+/g, " ") + ", " : "";
  L.push(`  app.use("${r.mount}", ${guards}require("../server/routes/${r.mod}"));`);
}
L.push("  return app;");
L.push("}");
L.push("");
L.push("module.exports = { buildApp, runtime, Res: express.Res };");

fs.writeFileSync(OUT, L.join("\n") + "\n");
console.log(`wrote src/app.cjs with ${kept.length} mounts (skipped ${rows.length - kept.length})`);

const guarded = kept.filter((r) => r.guards).length;
console.log(`  guarded mounts: ${guarded}   unguarded: ${kept.length - guarded}`);
for (const r of kept.filter((x) => !x.guards)) console.log(`    UNGUARDED: ${r.mount}`);
