/* GENERATED by tools/gen-app.js — do not edit by hand.
   57 of 58 mounts; /api/auth is handled by the Worker.
   Regenerate after any change to server/index.js. */
const express = require("./express-shim.cjs");
const { requireAuth, requireRole } = require("../server/auth");
/* Re-exported so the Durable Object uses the SAME module instance the
   route files do. Reaching _runtime through a separate ESM import()
   creates a second AsyncLocalStorage, and a store set on one is
   invisible to the other — which presents as "used outside a request"
   on every route while the wiring looks correct. */
const runtime = require("../server/_runtime");

function buildApp() {
  const app = express.Router();
  app.use("/api/license", requireAuth, require("../server/routes/license"));
  app.use("/api/businesses", requireAuth, require("../server/routes/businesses"));
  app.use("/api/settings", requireAuth, require("../server/routes/settings"));
  app.use("/api/products", requireAuth, require("../server/routes/products"));
  app.use("/api/customers", requireAuth, require("../server/routes/customers"));
  app.use("/api/suppliers", requireAuth, require("../server/routes/suppliers"));
  app.use("/api/invoices", requireAuth, require("../server/routes/invoices"));
  app.use("/api/reports", requireAuth, require("../server/routes/reports"));
  app.use("/api/accounting", requireAuth, require("../server/routes/accounting"));
  app.use("/api/ewaybill", requireAuth, require("../server/routes/ewaybill"));
  app.use("/api/ewb", requireAuth, require("../server/routes/ewb"));
  app.use("/api/data-health", requireAuth, require("../server/routes/dataHealth"));
  app.use("/api/gst", requireAuth, require("../server/routes/gst"));
  app.use("/api/product-query", requireAuth, require("../server/routes/productQuery"));
  app.use("/api/export", requireAuth, require("../server/routes/export"));
  app.use("/api/areas", requireAuth, require("../server/routes/areas"));
  app.use("/api/dispatch", requireAuth, require("../server/routes/dispatch"));
  app.use("/api/delivery", requireAuth, require("../server/routes/delivery"));
  app.use("/api/alerts", requireAuth, require("../server/routes/alerts"));
  app.use("/api/reminders", requireAuth, require("../server/routes/reminders"));
  app.use("/api/notes", requireAuth, require("../server/routes/notes"));
  app.use("/api/categories", requireAuth, require("../server/routes/categories"));
  app.use("/api/cashbook", requireAuth, require("../server/routes/cashbook"));
  app.use("/api/employees", requireAuth, requireRole("owner"), require("../server/routes/employees"));
  app.use("/api/bankbook", requireAuth, require("../server/routes/bankbook"));
  app.use("/api/bank-accounts", requireAuth, require("../server/routes/bankAccounts"));
  app.use("/api/cheques", requireAuth, require("../server/routes/cheques"));
  app.use("/api/inquiries", requireAuth, require("../server/routes/inquiries"));
  app.use("/api/purchases", requireAuth, require("../server/routes/purchases"));
  app.use("/api/purchase-orders", requireAuth, require("../server/routes/purchaseOrders"));
  app.use("/api/selection-slips", requireAuth, require("../server/routes/selectionSlips"));
  app.use("/api/whatsapp", requireAuth, require("../server/routes/whatsapp"));
  app.use("/api/tally-bridge", require("../server/routes/tallyBridge"));
  app.use("/api/tally", requireAuth, require("../server/routes/tally"));
  app.use("/api/gst-filings", requireAuth, require("../server/routes/gstFilings"));
  app.use("/api/price-lists", requireAuth, require("../server/routes/priceLists"));
  app.use("/api/quotations", requireAuth, require("../server/routes/quotations"));
  app.use("/api/sales-orders", requireAuth, require("../server/routes/salesOrders"));
  app.use("/api/sales-returns", requireAuth, require("../server/routes/salesReturns"));
  app.use("/api/purchase-returns", requireAuth, require("../server/routes/purchaseReturns"));
  app.use("/api/stock-ins", requireAuth, require("../server/routes/stockIns"));
  app.use("/api/locations", requireAuth, require("../server/routes/locations"));
  app.use("/api/transfers", requireAuth, require("../server/routes/transfers"));
  app.use("/api/stock-history", requireAuth, require("../server/routes/stockHistory"));
  app.use("/api/position", requireAuth, require("../server/routes/position"));
  app.use("/api/material-flow", requireAuth, require("../server/routes/materialFlow"));
  app.use("/api/bill-scan", requireAuth, require("../server/routes/billScan"));
  app.use("/api/permissions", requireAuth, require("../server/routes/permissions"));
  app.use("/api/staff", requireAuth, requireRole("owner"), require("../server/routes/staff"));
  app.use("/api/audit", requireAuth, requireRole("owner"), require("../server/routes/audit"));
  app.use("/api/backup", requireAuth, requireRole("owner"), require("../server/routes/backup"));
  app.use("/api/print", requireAuth, require("../server/routes/print"));
  app.use("/api/print-manager", requireAuth, require("../server/routes/printManager"));
  app.use("/api/numbering", requireAuth, require("../server/routes/numbering"));
  app.use("/api/attachments", requireAuth, require("../server/routes/attachments"));
  app.use("/api/reset", requireAuth, requireRole("owner"), require("../server/routes/reset"));
  app.use("/api/financial-years", requireAuth, requireRole("owner"), require("../server/routes/financialYears"));
  return app;
}

module.exports = { buildApp, runtime, Res: express.Res };
